name: GitHub action test

on:
  pull_request: null

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "Print: $BRANCH_NAME"

        env:
          NAME: ${{ github.event.pull_request.head.ref }}
          BRANCH_NAME: ${{ NAME }}////-